[versions]
sdkVersion = "31"
minSdkVersion = "21"
ksp = "1.8.0-1.0.9"
kotlinpoet_version = "1.17.0"
javapoet_version = "1.13.0"
gradle_version = "7.4.1"
javassist_version = "3.30.2-GA"
asm_version = "9.7"
gson = "2.10.1"
core-ktx = "1.6.0"
junit = "4.13.2"
appcompat = "1.6.1"
annotation = "1.3.0"
material = "1.6.0"
leakcanary_version = "2.7"
bcprov-jdk15on-version = "1.68"
rxpermissions = "0.12"
rxjava = "3.0.4"
kotlin = "1.8.0"
junit-junit = "4.13.2"
androidx-test-ext-junit = "1.2.1"
espresso-core = "3.6.1"
test-rules = "1.5.0"
flyjingfish_javassist_version = "1.0.1"
[libraries]
kotlinpoet-ksp = { group = "com.squareup", name = "kotlinpoet-ksp", version.ref = "kotlinpoet_version" }
kotlinpoet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlinpoet_version" }
javapoet = { group = "com.squareup", name = "javapoet", version.ref = "javapoet_version" }
ksp-api = { group = "com.google.devtools.ksp", name = "symbol-processing-api", version.ref = "ksp" }
javassist = { group = "org.javassist", name = "javassist", version.ref = "javassist_version" }
asm-lib = { group = "org.ow2.asm", name = "asm", version.ref = "asm_version" }
asm-commons = { group = "org.ow2.asm", name = "asm-commons", version.ref = "asm_version" }
gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "gradle_version" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
leakcanary = { group = "com.squareup.leakcanary", name = "leakcanary-android", version.ref = "leakcanary_version" }
bcprov-jdk15on = { group = "org.bouncycastle", name = "bcprov-jdk15on", version.ref = "bcprov-jdk15on-version" }
rxpermissions = { group = "com.github.tbruyelle", name = "rxpermissions", version.ref = "rxpermissions" }
rxjava = { group = "io.reactivex.rxjava3", name = "rxjava", version.ref = "rxjava" }
kotlin-stdLib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
junit = { group = "junit", name = "junit", version.ref = "junit-junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
androidx-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
flyjingfish-javassist = { group = "io.github.FlyJingFish.javassist", name = "javassist", version.ref = "flyjingfish_javassist_version" }
